spring:
  application:
    name: task-tracker-email-sender

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: "task-tracker-email-sender-v1"
      auto-offset-reset: latest
      properties:
        session.timeout.ms: 45000
        heartbeat.interval.ms: 10000
        max.poll.interval.ms: 300000

app:
  instance-id: ${APP_INSTANCE_ID}
  email:
    sender-address: "noreply@tasktracker.com"
    kafka-topic: "task_tracker.notifications.email_commands"
    retry-topic: "task_tracker.notifications.email_commands-recovery"
    dlt-topic: "task_tracker.notifications.email_commands-dlt"

    message-validity:
      default-duration: 7d
      policies:
        USER_WELCOME: 30m
        DAILY_TASK_REPORT: 8h