spring:
  application:
    name: task-tracker-email-sender

  data:
    redis:
      host: overrideItLocal
  kafka:
    bootstrap-servers: overrideItLocal

app:
  observability:
    enabled: true

management:
  defaults:
    metrics:
      export:
        enabled: false
  tracing:
    enabled: false
  logging:
    export:
      enabled: false


logging:
  level:
    root: warn
    com.example.tasktracker.emailsender: debug
