spring:
  application:
    name: task-tracker-email-sender

  data:
    redis:
      host: overrideItLocal
  kafka:
    bootstrap-servers: overrideItLocal

logging:
  level:
    root: warn
    com.example.tasktracker.emailsender: debug
