apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus_ds
    
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki_ds    
    jsonData:
      derivedFields:
        - datasourceUid: tempo_ds
          matcherRegex: '"traceid":"([0-9a-fA-F]{32})"'
          name: 'TraceID'
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace in Tempo'

        - matcherRegex: '"instrumentation_scope":\s*\{\s*"name":"([^"]+)"'
          name: 'Logger'

        - matcherRegex: '"body":"((?:[^"]|\\")*)"'
          name: 'Message'

        - matcherRegex: '"severity":"([^"]*)"' # Стандартное поле ECS для уровня лога
          name: 'Level'

  - name: Tempo
    type: tempo
    uid: tempo_ds
    url: http://tempo:3200
    access: proxy
    basicAuth: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki_ds'
        spanStartTimeShift: '-30s'
        spanEndTimeShift: '30s'
        filterByTraceID: true
        filterBySpanID: false
        customQuery: true
        query: '{service_name="$${__span.tags["service.name"]}"} | json | traceid = "$${__trace.traceId}"'
      serviceMap:
        datasourceUid: 'prometheus_ds'
      nodeGraph:
        enable: false