receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:
    send_batch_size: 1024
    timeout: 10s

exporters:
  # --- Экспортер для МЕТРИК ---
  prometheus:
    endpoint: 0.0.0.0:8889

  # --- Экспортер для ТРЕЙСОВ ---
  otlphttp/tempo:
    endpoint: http://tempo:4318
    tls:
      insecure: true
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  debug:
    verbosity: detailed # Уровни: basic, normal, detailed

service:
  pipelines:
    # --- Pipeline для МЕТРИК ---
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    # --- Pipeline для ТРЕЙСОВ ---
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/tempo, debug]

    # --- Pipeline для ЛОГОВ ---
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]
