global:
  scrape_interval: 15s # Как часто собирать метрики

scrape_configs:
  - job_name: 'otel-collector' # Имя задачи для метрик, собранных OTel Collector
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889'] # Адрес и порт экспортера Prometheus в OTel Collector
