spring:
  datasource:
    username: devuser
    password: devpass
logging:
  level:
    com.example.tasktracker.backend: DEBUG
    org.springframework: INFO
    org.hibernate: WARN

#TODO принять решение о минимальном observability стеке на ci. например коллектор с экспортом в stdout и/или файл;
#TODO  стриминг из коллектора на поднятный Obs stack
otel:
  sdk:
    disabled: true
