spring:
  application:
    name:
      task-tracker-backend
  datasource:
    url: jdbc:postgresql://postgres:5432/task_tracker_db
    username:
      file: /run/secrets/postgres_user
    password:
      file: /run/secrets/postgres_password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  messages:
    basename: i18n/security/messages, i18n/user/messages
    encoding: UTF-8
    fallback-to-system-locale: false


logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info
  # Отключим метрики JMX, если не нужны
  jmx:
    enabled: false
  # Настроим теги, которые будут добавляться ко всем метрикам

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://otel-collector:4318 # OTLP/HTTP
  instrumentation:
    common:
      default-enabled: true
    micrometer:
      enabled: true
    logback-appender:
      enabled: true
      experimental:
        capture-mdc-attributes: "*"
  propagators: tracecontext,baggage
  traces:
    sampler:
      arg: "0.1"

app:
  security:
    jwt:
      expiration-ms: 3600000 # 1 час