spring:
  application:
    name:
      task-tracker-backend
  datasource:
    url: jdbc:postgresql://postgres:5432/task_tracker_db
    username:
      file: /run/secrets/postgres_user
    password:
      file: /run/secrets/postgres_password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  messages:
    basename: i18n/common/messages,i18n/security/messages, i18n/user/messages, i18n/task/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  kafka:
    bootstrap-servers: kafka:9092 # Адрес Kafka-брокера из docker-compose.yml
    admin:
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2
      properties:
        spring.json.add.type.headers: false # Не добавлять заголовки с информацией о типе Java-класса
        # Таймауты и надежность
        delivery.timeout.ms: 50000 # общий таймаут на доставку сообщения, включая ретраи
        request.timeout.ms: 15000   # 30 секунд - таймаут на один запрос к брокеру
        max.block.ms: 30000       # 1 минута - максимальное время блокировки send()
        enable.idempotence: false

server:
  error:
    include-message: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info
  # Отключим метрики JMX, если не нужны
  jmx:
    enabled: false
  # Настроим теги, которые будут добавляться ко всем метрикам

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://otel-collector:4318 # OTLP/HTTP
  instrumentation:
    common:
      default-enabled: true
    micrometer:
      enabled: true
    logback-appender:
      enabled: true
      experimental:
        capture-mdc-attributes: "*"
  propagators: tracecontext,baggage
  traces:
    sampler:
      arg: "0.1"

app:
  kafka:
    topic:
      email-commands:
        name: "EMAIL_SENDING_TASKS"
  security:
    jwt:
      expiration-ms: 3600000 # 1 час