spring:
  datasource:
    username: devuser
    password: devpass
  logging:
    level:
      com.example.tasktracker.backend: DEBUG
      org.springframework: INFO
      org.hibernate: WARN
    pattern: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

otel:
  sdk:
    disabled: true

  endpoints:
    web:
      exposure:
        include: health
