spring:
  application:
    name:
      task-tracker-backend
  datasource:
    url: jdbc:postgresql://task-tracker-postgres:5432/task_tracker_db
    username: ${postgres_user}
    password: ${postgres_password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  messages:
    basename: i18n/internal/messages,i18n/config/validation,i18n/common/messages,i18n/security/messages, i18n/user/messages, i18n/task/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  kafka:
    bootstrap-servers: task-tracker-kafka:9092
    admin:
      fail-fast: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 2
      properties:
        spring.json.add.type.headers: false
        delivery.timeout.ms: 50000
        request.timeout.ms: 15000
        max.block.ms: 30000
        enable.idempotence: false

server:
  error:
    include-message: never
    include-stacktrace: never
    include-exception: false
    whitelabel:
      enabled: false

logging:
  structured:
    format:
      console: ecs
  level:
    root: INFO

management:
  server:
    port: ${MANAGEMENT_PORT:8081}
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health, info
  jmx:
    metrics:
      export:
        enabled: false

otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://task-tracker-otel-collector:4318
  instrumentation:
    common:
      default-enabled: true
    micrometer:
      enabled: true
    logback-appender:
      enabled: true
      experimental:
        capture-mdc-attributes: "*"
  propagators: tracecontext,baggage
  traces:
    sampler:
      arg: "0.1"

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

app:
  kafka:
    topic-verifier:
      enabled: true
    topic:
      email-commands:
        name: "task_tracker.notifications.email_commands"
  security:
    jwt:
      expiration-ms: 3600000 # 1 час
      secret-key: ${jwt_secret}
  internal-api:
    scheduler-support:
      user-processing-ids:
        default-page-size: 1000
        max-page-size: 5000