logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.data.jpa.repository.query: DEBUG
    com.example.tasktracker.backend: DEBUG

server:
  error:
    include-stacktrace: on_param
    include-message: on_param
    include-binding-errors: on_param
    include-exception: true
    whitelabel.enabled: true

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true

#TODO принять решение о минимальном observability стеке на ci. например коллектор с экспортом в stdout и/или файл;
#TODO  стриминг из коллектора на поднятный Obs stack

app:
  kafka:
    topic-verifier:
      enabled: false
  security:
    jwt:
      # Пример Base64 ключа (реальный ключ должен быть сгенерирован и быть длиннее для HS256)
      # Это "myVerySecretKeyForTaskTrackerApplicationWhichMustBeVeryLongAndSecure" в Base64
      secret-key: "bXlWZXJ5U2VjcmV0S2V5Rm9yVGFza1RyYWNrZXJBcHBsaWNhdGlvbldoaWNoTXVzdEJlVmVyeUxvbmdBbmRTZWN1cmU="