spring:
  datasource:
    username: devuser
    password: devpass
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.data.jpa.repository.query: DEBUG
    com.example.tasktracker.backend: DEBUG
  structured:
    format:
      console: ecs

server:
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
    include-exception: true
    whitelabel.enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, env, loggers
  jmx:
    enabled: true

otel:
  traces:
    sampler:
      arg: "1.0"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

app:
  security:
    jwt:
      # Пример Base64 ключа (реальный ключ должен быть сгенерирован и быть длиннее для HS256)
      # Это "myVerySecretKeyForTaskTrackerApplicationWhichMustBeVeryLongAndSecure" в Base64
      secret-key: "bXlWZXJ5U2VjcmV0S2V5Rm9yVGFza1RyYWNrZXJBcHBsaWNhdGlvbldoaWNoTXVzdEJlVmVyeUxvbmdBbmRTZWN1cmU="
    api-key:
      valid-keys:
        - "dev-api-key-for-internal-services"
