app:
  scheduler:
    backend-client:
      api-key: "${BACKEND_API_KEY:key-for-scheduler}"
    jobs:
      daily-task-reports:
        enabled: false
    consumers:
      daily-report:
        enabled: false

logging:
  level:
    root:
    com.example.tasktracker: