{
 "title": "General dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_type", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  { "title": "rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "income rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (span_name) (\r\n  rate(traces_span_metrics_calls_total{\r\n    exported_job=~\"$service_type\", \r\n    span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\"\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outcome rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (db_system_name, messaging_system, peer_service) (\r\n  rate(traces_span_metrics_calls_total{\r\n    exported_job=~\"$service_type\", \r\n    span_kind=~\"SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER\",\r\n  }[$__rate_interval])\r\n)",
     "legendFormat": "{{db_system_name}}{{messaging_system}}{{peer_service}}"
    }
   ]
  },
  { "title": "error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "error chart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(traces_span_metrics_calls_total{exported_job=~\"$service_type\", status_code=\"STATUS_CODE_ERROR\"}[5m])) \r\n  * 100 \r\n  / \r\n  (sum(rate(traces_span_metrics_calls_total{exported_job=~\"$service_type\"}[5m])) > 0)\r\n) \r\nOR on() vector(0)",
     "legendFormat": "error rate"
    },
    {
     "expr": "sum(rate(traces_span_metrics_calls_total{exported_job=~\"$service_type\"}[$__rate_interval]))",
     "legendFormat": "total rate"
    }
   ]
  },
  {
   "title": "error rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(traces_span_metrics_calls_total{exported_job=~\"$service_type\", status_code=\"STATUS_CODE_ERROR\"}[5m])) \r\n  * 100 \r\n  / \r\n  (sum(rate(traces_span_metrics_calls_total{exported_job=~\"$service_type\"}[5m])) > 0)\r\n) \r\nOR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Exceptions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "err/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(exception_type) (rate(traces_span_metrics_events_total{exported_job=~\"$service_type\"}[5m]))) * 60 > 0",
     "legendFormat": "{{exception_type}}"
    }
   ]
  },
  { "title": "saturation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "messaging consumer lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pcs" } },
   "targets": [
    {
     "expr": "topk(5, sum by(topic) (kafka_consumer_group_lag_ratio))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "thread pool saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(name) (executor_queued_tasks{exported_job=~\"$service_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "hikariCp waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(exported_job) (hikaricp_connections_pending{exported_job=~\"$service_type\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Throttling / Wait",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(system_cpu_utilization_ratio{state=~\"steal|wait\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Overhead",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{exported_job=~\"$service_type\"}[$__rate_interval])) \r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "income p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n  sum by (le, span_name) (\r\n    rate(traces_span_metrics_duration_milliseconds_bucket{\r\n      exported_job=~\"$service_type\", \r\n      span_kind=~\"SPAN_KIND_SERVER|SPAN_KIND_CONSUMER\"\r\n    }[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "outcome p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \r\n  sum by (le, span_name) (\r\n    rate(traces_span_metrics_duration_milliseconds_bucket{\r\n      exported_job=~\"$service_type\", \r\n      span_kind=~\"SPAN_KIND_CLIENT|SPAN_KIND_PRODUCER\"\r\n    }[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}